---
config:
  flowchart:
    curve: linear
---
graph TD;
	__start__([<p>__start__</p>]):::first
	build_retrieval_plan(build_retrieval_plan)
	rag_executor(rag_executor)
	filter_rag(filter_rag)
	rerank_rag(rerank_rag)
	build_evidence_pack(build_evidence_pack)
	finalize_rag(finalize_rag)
	__end__([<p>__end__</p>]):::last
	__start__ --> build_retrieval_plan;
	build_evidence_pack --> finalize_rag;
	build_retrieval_plan --> rag_executor;
	filter_rag --> rerank_rag;
	rag_executor --> filter_rag;
	rerank_rag --> build_evidence_pack;
	finalize_rag --> __end__;
	classDef default fill:#f2f0ff,line-height:1.2
	classDef first fill-opacity:0
	classDef last fill:#bfb6fc
