from .stages_front import WorkflowNodeAdapterStagesFrontMixin
from .stages_back import WorkflowNodeAdapterStagesBackMixin


class WorkflowNodeAdapterStagesMixin(WorkflowNodeAdapterStagesFrontMixin, WorkflowNodeAdapterStagesBackMixin):
    pass
