from __future__ import annotations

from importlib import import_module
from typing import TYPE_CHECKING, Any

if TYPE_CHECKING:  # pragma: no cover - import-time typing only
    from .contracts import (
        AnswerComposeRequest,
        AnswerComposeResult,
        AnswerContract,
        AnswerPlan,
        AnswerVerifierResult,
        ChatTurnCommand,
        Citation,
        CitationBuildRequest,
        ClarificationCard,
        ClarificationOption,
        EntityJoinResult,
        ErrorPayload,
        EvidenceEvaluationRequest,
        EvidenceItem,
        EvidencePack,
        EvidenceQualityDecision,
        FastDecision,
        FacetPlan,
        FinalPayload,
        GraphRuntimeMeta,
        HybridRecallCandidate,
        HybridRecallResult,
        HybridRetrieveRequest,
        InputQualityDecision,
        IntentRoutingDecision,
        LoopCounter,
        KnowledgeSearchRequest,
        KnowledgeSearchResult,
        MasteryUpdateCommand,
        MasteryUpdateResult,
        MemoryUpdateSummary,
        MemoryUsedItemSummary,
        MemoryUsedSummary,
        MemoryWriteResult,
        MemoryWriteTargetResult,
        NormalizedToolResult,
        PersistentSessionContext,
        PersistSessionCommand,
        PersistSessionResult,
        PlanExecutionSummary,
        PlanStep,
        QueryRewriteRequest,
        RagResult,
        ReferenceResolutionRequest,
        ReferenceResolutionResult,
        ReviewReport,
        RetrievalEligibility,
        RetrievalPlan,
        RetrievalSummary,
        RewriteDecision,
        RoutingDecision,
        RoutingContract,
        SemanticParseResult,
        SourceContract,
        SseEnvelope,
        StepResult,
        TaskPlan,
        ToolExecutionCommand,
        ToolExecutionResult,
        ToolNormalizationRequest,
        ToolPlanningRequest,
        ToolSelection,
        TurnRuntimeState,
        TurnUnderstandingRequest,
        TurnUnderstandingResult,
    )
    from .enums import IntentType, OutputStyle, RagStatus, ToolExecutionStatus, TurnDecision
    from .errors import ErrorInfo, TerminalEvent, WorkflowErrorCode, build_error
    from .memory import (
        EntityMemoryStore,
        EpisodicMemoryRecord,
        LongTermMemoryStore,
        MemoryAccessLog,
        MemoryCandidate,
        MemoryConflict,
        MemoryConsolidationPlan,
        MemoryCoreModel,
        MemoryDeletionJob,
        MemoryDeletionStatus,
        MemoryEdge,
        MemoryEdgeType,
        MemoryInjectionPlan,
        MemoryMetadata,
        MemoryPersistenceScope,
        MemoryRecord,
        MemoryRetrievalMode,
        MemoryRetrievalPlan,
        MemoryScope,
        MemorySensitivity,
        MemorySource,
        MemoryStatus,
        MemoryTargetStore,
        MemoryTrace,
        MemoryType,
        MemoryUpdateEvent,
        MemoryWritePlan,
        ProceduralMemoryRecord,
        RetrievedMemoryPack,
        SemanticMemoryRecord,
        SensoryMemoryBuffer,
        SensoryMemoryRecord,
        SessionMemoryStore,
        SessionSummaryMemoryRecord,
        ShortTermMemoryStore,
        UserPreferenceMemoryRecord,
    )
    from .state import GraphState, build_initial_state, clone_graph_state

__all__ = [
    "AnswerPlan",
    "AnswerComposeRequest",
    "AnswerComposeResult",
    "AnswerContract",
    "AnswerVerifierResult",
    "ChatTurnCommand",
    "Citation",
    "CitationBuildRequest",
    "ClarificationCard",
    "ClarificationOption",
    "ErrorInfo",
    "ErrorPayload",
    "EvidenceEvaluationRequest",
    "EvidenceItem",
    "EvidencePack",
    "EvidenceQualityDecision",
    "FinalPayload",
    "FastDecision",
    "GraphRuntimeMeta",
    "GraphState",
    "HybridRecallCandidate",
    "HybridRecallResult",
    "HybridRetrieveRequest",
    "IntentType",
    "EntityJoinResult",
    "LoopCounter",
    "KnowledgeSearchRequest",
    "KnowledgeSearchResult",
    "MasteryUpdateCommand",
    "MasteryUpdateResult",
    "MemoryUsedItemSummary",
    "MemoryUsedSummary",
    "MemoryUpdateSummary",
    "MemoryWriteResult",
    "MemoryWriteTargetResult",
    "InputQualityDecision",
    "IntentRoutingDecision",
    "PlanExecutionSummary",
    "PlanStep",
    "NormalizedToolResult",
    "OutputStyle",
    "PersistentSessionContext",
    "PersistSessionCommand",
    "PersistSessionResult",
    "RagStatus",
    "RagResult",
    "ReferenceResolutionRequest",
    "ReferenceResolutionResult",
    "ReviewReport",
    "QueryRewriteRequest",
    "RetrievalEligibility",
    "RetrievalSummary",
    "RetrievalPlan",
    "RewriteDecision",
    "SseEnvelope",
    "TerminalEvent",
    "ToolExecutionCommand",
    "ToolExecutionResult",
    "ToolNormalizationRequest",
    "ToolPlanningRequest",
    "TaskPlan",
    "ToolExecutionStatus",
    "ToolSelection",
    "StepResult",
    "TurnDecision",
    "TurnUnderstandingRequest",
    "TurnRuntimeState",
    "TurnUnderstandingResult",
    "RoutingDecision",
    "RoutingContract",
    "SemanticParseResult",
    "SourceContract",
    "WorkflowErrorCode",
    "build_error",
    "build_initial_state",
    "clone_graph_state",
    "EntityMemoryStore",
    "EpisodicMemoryRecord",
    "LongTermMemoryStore",
    "MemoryCandidate",
    "MemoryAccessLog",
    "MemoryDeletionJob",
    "MemoryDeletionStatus",
    "MemoryEdge",
    "MemoryEdgeType",
    "MemoryConflict",
    "MemoryConsolidationPlan",
    "MemoryCoreModel",
    "MemoryInjectionPlan",
    "MemoryMetadata",
    "MemoryRecord",
    "MemoryRetrievalPlan",
    "MemoryPersistenceScope",
    "MemoryRetrievalMode",
    "MemoryScope",
    "MemorySource",
    "MemorySensitivity",
    "MemoryStatus",
    "MemoryTargetStore",
    "MemoryType",
    "MemoryTrace",
    "MemoryUpdateEvent",
    "MemoryWritePlan",
    "ProceduralMemoryRecord",
    "RetrievedMemoryPack",
    "ShortTermMemoryStore",
    "SessionMemoryStore",
    "SessionSummaryMemoryRecord",
    "SensoryMemoryBuffer",
    "SensoryMemoryRecord",
    "SemanticMemoryRecord",
    "UserPreferenceMemoryRecord",
]

_MODULE_MAP: dict[str, str] = {
    # contracts
    "AnswerComposeRequest": "contracts",
    "AnswerComposeResult": "contracts",
    "AnswerContract": "contracts",
    "AnswerPlan": "contracts",
    "AnswerVerifierResult": "contracts",
    "ChatTurnCommand": "contracts",
    "Citation": "contracts",
    "CitationBuildRequest": "contracts",
    "ClarificationCard": "contracts",
    "ClarificationOption": "contracts",
    "EntityJoinResult": "contracts",
    "ErrorPayload": "contracts",
    "EvidenceEvaluationRequest": "contracts",
    "EvidenceItem": "contracts",
    "EvidencePack": "contracts",
    "EvidenceQualityDecision": "contracts",
    "FastDecision": "contracts",
    "FacetPlan": "contracts",
    "FinalPayload": "contracts",
    "GraphRuntimeMeta": "contracts",
    "HybridRecallCandidate": "contracts",
    "HybridRecallResult": "contracts",
    "HybridRetrieveRequest": "contracts",
    "InputQualityDecision": "contracts",
    "IntentRoutingDecision": "contracts",
    "LoopCounter": "contracts",
    "KnowledgeSearchRequest": "contracts",
    "KnowledgeSearchResult": "contracts",
    "MasteryUpdateCommand": "contracts",
    "MasteryUpdateResult": "contracts",
    "MemoryUpdateSummary": "contracts",
    "MemoryUsedItemSummary": "contracts",
    "MemoryUsedSummary": "contracts",
    "MemoryWriteResult": "contracts",
    "MemoryWriteTargetResult": "contracts",
    "NormalizedToolResult": "contracts",
    "PersistentSessionContext": "contracts",
    "PersistSessionCommand": "contracts",
    "PersistSessionResult": "contracts",
    "PlanExecutionSummary": "contracts",
    "PlanStep": "contracts",
    "QueryRewriteRequest": "contracts",
    "RagResult": "contracts",
    "ReferenceResolutionRequest": "contracts",
    "ReferenceResolutionResult": "contracts",
    "ReviewReport": "contracts",
    "RetrievalEligibility": "contracts",
    "RetrievalPlan": "contracts",
    "RetrievalSummary": "contracts",
    "RewriteDecision": "contracts",
    "RoutingDecision": "contracts",
    "RoutingContract": "contracts",
    "SemanticParseResult": "contracts",
    "SourceContract": "contracts",
    "SseEnvelope": "contracts",
    "StepResult": "contracts",
    "TaskPlan": "contracts",
    "ToolExecutionCommand": "contracts",
    "ToolExecutionResult": "contracts",
    "ToolNormalizationRequest": "contracts",
    "ToolPlanningRequest": "contracts",
    "ToolSelection": "contracts",
    "TurnRuntimeState": "contracts",
    "TurnUnderstandingRequest": "contracts",
    "TurnUnderstandingResult": "contracts",
    # enums
    "IntentType": "enums",
    "OutputStyle": "enums",
    "RagStatus": "enums",
    "ToolExecutionStatus": "enums",
    "TurnDecision": "enums",
    # errors
    "ErrorInfo": "errors",
    "TerminalEvent": "errors",
    "WorkflowErrorCode": "errors",
    "build_error": "errors",
    # memory
    "EntityMemoryStore": "memory",
    "EpisodicMemoryRecord": "memory",
    "LongTermMemoryStore": "memory",
    "MemoryAccessLog": "memory",
    "MemoryCandidate": "memory",
    "MemoryConflict": "memory",
    "MemoryConsolidationPlan": "memory",
    "MemoryCoreModel": "memory",
    "MemoryDeletionJob": "memory",
    "MemoryDeletionStatus": "memory",
    "MemoryEdge": "memory",
    "MemoryEdgeType": "memory",
    "MemoryInjectionPlan": "memory",
    "MemoryMetadata": "memory",
    "MemoryPersistenceScope": "memory",
    "MemoryRecord": "memory",
    "MemoryRetrievalMode": "memory",
    "MemoryRetrievalPlan": "memory",
    "MemoryScope": "memory",
    "MemorySensitivity": "memory",
    "MemorySource": "memory",
    "MemoryStatus": "memory",
    "MemoryTargetStore": "memory",
    "MemoryTrace": "memory",
    "MemoryType": "memory",
    "MemoryUpdateEvent": "memory",
    "MemoryWritePlan": "memory",
    "ProceduralMemoryRecord": "memory",
    "RetrievedMemoryPack": "memory",
    "SemanticMemoryRecord": "memory",
    "SensoryMemoryBuffer": "memory",
    "SensoryMemoryRecord": "memory",
    "SessionMemoryStore": "memory",
    "SessionSummaryMemoryRecord": "memory",
    "ShortTermMemoryStore": "memory",
    "UserPreferenceMemoryRecord": "memory",
    # state
    "GraphState": "state",
    "build_initial_state": "state",
    "clone_graph_state": "state",
}


def __getattr__(name: str) -> Any:
    module_name = _MODULE_MAP.get(name)
    if not module_name:
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
    module = import_module(f".{module_name}", __name__)
    value = getattr(module, name)
    globals()[name] = value
    return value
