// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.20.3
// source: main.proto

package aisp_core_grpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	AispCoreService_CreateConversation_FullMethodName   = "/luca.aisp.core.AispCoreService/CreateConversation"
	AispCoreService_GetConversation_FullMethodName      = "/luca.aisp.core.AispCoreService/GetConversation"
	AispCoreService_DeleteConversation_FullMethodName   = "/luca.aisp.core.AispCoreService/DeleteConversation"
	AispCoreService_CreateDialogue_FullMethodName       = "/luca.aisp.core.AispCoreService/CreateDialogue"
	AispCoreService_CreateDialogueStream_FullMethodName = "/luca.aisp.core.AispCoreService/CreateDialogueStream"
	AispCoreService_GetDialogue_FullMethodName          = "/luca.aisp.core.AispCoreService/GetDialogue"
)

// AispCoreServiceClient is the client API for AispCoreService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AispCoreServiceClient interface {
	CreateConversation(ctx context.Context, in *CreateConversationRequest, opts ...grpc.CallOption) (*Conversation, error)
	GetConversation(ctx context.Context, in *GetConversationRequest, opts ...grpc.CallOption) (*Conversation, error)
	DeleteConversation(ctx context.Context, in *DeleteConversationRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	CreateDialogue(ctx context.Context, in *CreateDialogueRequest, opts ...grpc.CallOption) (*Dialogue, error)
	CreateDialogueStream(ctx context.Context, in *CreateDialogueRequest, opts ...grpc.CallOption) (AispCoreService_CreateDialogueStreamClient, error)
	GetDialogue(ctx context.Context, in *GetDialogueRequest, opts ...grpc.CallOption) (*Dialogue, error)
}

type aispCoreServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAispCoreServiceClient(cc grpc.ClientConnInterface) AispCoreServiceClient {
	return &aispCoreServiceClient{cc}
}

func (c *aispCoreServiceClient) CreateConversation(ctx context.Context, in *CreateConversationRequest, opts ...grpc.CallOption) (*Conversation, error) {
	out := new(Conversation)
	err := c.cc.Invoke(ctx, AispCoreService_CreateConversation_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aispCoreServiceClient) GetConversation(ctx context.Context, in *GetConversationRequest, opts ...grpc.CallOption) (*Conversation, error) {
	out := new(Conversation)
	err := c.cc.Invoke(ctx, AispCoreService_GetConversation_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aispCoreServiceClient) DeleteConversation(ctx context.Context, in *DeleteConversationRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, AispCoreService_DeleteConversation_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aispCoreServiceClient) CreateDialogue(ctx context.Context, in *CreateDialogueRequest, opts ...grpc.CallOption) (*Dialogue, error) {
	out := new(Dialogue)
	err := c.cc.Invoke(ctx, AispCoreService_CreateDialogue_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aispCoreServiceClient) CreateDialogueStream(ctx context.Context, in *CreateDialogueRequest, opts ...grpc.CallOption) (AispCoreService_CreateDialogueStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &AispCoreService_ServiceDesc.Streams[0], AispCoreService_CreateDialogueStream_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &aispCoreServiceCreateDialogueStreamClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type AispCoreService_CreateDialogueStreamClient interface {
	Recv() (*Dialogue, error)
	grpc.ClientStream
}

type aispCoreServiceCreateDialogueStreamClient struct {
	grpc.ClientStream
}

func (x *aispCoreServiceCreateDialogueStreamClient) Recv() (*Dialogue, error) {
	m := new(Dialogue)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *aispCoreServiceClient) GetDialogue(ctx context.Context, in *GetDialogueRequest, opts ...grpc.CallOption) (*Dialogue, error) {
	out := new(Dialogue)
	err := c.cc.Invoke(ctx, AispCoreService_GetDialogue_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AispCoreServiceServer is the server API for AispCoreService service.
// All implementations must embed UnimplementedAispCoreServiceServer
// for forward compatibility
type AispCoreServiceServer interface {
	CreateConversation(context.Context, *CreateConversationRequest) (*Conversation, error)
	GetConversation(context.Context, *GetConversationRequest) (*Conversation, error)
	DeleteConversation(context.Context, *DeleteConversationRequest) (*emptypb.Empty, error)
	CreateDialogue(context.Context, *CreateDialogueRequest) (*Dialogue, error)
	CreateDialogueStream(*CreateDialogueRequest, AispCoreService_CreateDialogueStreamServer) error
	GetDialogue(context.Context, *GetDialogueRequest) (*Dialogue, error)
	mustEmbedUnimplementedAispCoreServiceServer()
}

// UnimplementedAispCoreServiceServer must be embedded to have forward compatible implementations.
type UnimplementedAispCoreServiceServer struct {
}

func (UnimplementedAispCoreServiceServer) CreateConversation(context.Context, *CreateConversationRequest) (*Conversation, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateConversation not implemented")
}
func (UnimplementedAispCoreServiceServer) GetConversation(context.Context, *GetConversationRequest) (*Conversation, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetConversation not implemented")
}
func (UnimplementedAispCoreServiceServer) DeleteConversation(context.Context, *DeleteConversationRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteConversation not implemented")
}
func (UnimplementedAispCoreServiceServer) CreateDialogue(context.Context, *CreateDialogueRequest) (*Dialogue, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateDialogue not implemented")
}
func (UnimplementedAispCoreServiceServer) CreateDialogueStream(*CreateDialogueRequest, AispCoreService_CreateDialogueStreamServer) error {
	return status.Errorf(codes.Unimplemented, "method CreateDialogueStream not implemented")
}
func (UnimplementedAispCoreServiceServer) GetDialogue(context.Context, *GetDialogueRequest) (*Dialogue, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDialogue not implemented")
}
func (UnimplementedAispCoreServiceServer) mustEmbedUnimplementedAispCoreServiceServer() {}

// UnsafeAispCoreServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AispCoreServiceServer will
// result in compilation errors.
type UnsafeAispCoreServiceServer interface {
	mustEmbedUnimplementedAispCoreServiceServer()
}

func RegisterAispCoreServiceServer(s grpc.ServiceRegistrar, srv AispCoreServiceServer) {
	s.RegisterService(&AispCoreService_ServiceDesc, srv)
}

func _AispCoreService_CreateConversation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateConversationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AispCoreServiceServer).CreateConversation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AispCoreService_CreateConversation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AispCoreServiceServer).CreateConversation(ctx, req.(*CreateConversationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AispCoreService_GetConversation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetConversationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AispCoreServiceServer).GetConversation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AispCoreService_GetConversation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AispCoreServiceServer).GetConversation(ctx, req.(*GetConversationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AispCoreService_DeleteConversation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteConversationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AispCoreServiceServer).DeleteConversation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AispCoreService_DeleteConversation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AispCoreServiceServer).DeleteConversation(ctx, req.(*DeleteConversationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AispCoreService_CreateDialogue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateDialogueRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AispCoreServiceServer).CreateDialogue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AispCoreService_CreateDialogue_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AispCoreServiceServer).CreateDialogue(ctx, req.(*CreateDialogueRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AispCoreService_CreateDialogueStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(CreateDialogueRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AispCoreServiceServer).CreateDialogueStream(m, &aispCoreServiceCreateDialogueStreamServer{stream})
}

type AispCoreService_CreateDialogueStreamServer interface {
	Send(*Dialogue) error
	grpc.ServerStream
}

type aispCoreServiceCreateDialogueStreamServer struct {
	grpc.ServerStream
}

func (x *aispCoreServiceCreateDialogueStreamServer) Send(m *Dialogue) error {
	return x.ServerStream.SendMsg(m)
}

func _AispCoreService_GetDialogue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDialogueRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AispCoreServiceServer).GetDialogue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AispCoreService_GetDialogue_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AispCoreServiceServer).GetDialogue(ctx, req.(*GetDialogueRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AispCoreService_ServiceDesc is the grpc.ServiceDesc for AispCoreService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AispCoreService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "luca.aisp.core.AispCoreService",
	HandlerType: (*AispCoreServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateConversation",
			Handler:    _AispCoreService_CreateConversation_Handler,
		},
		{
			MethodName: "GetConversation",
			Handler:    _AispCoreService_GetConversation_Handler,
		},
		{
			MethodName: "DeleteConversation",
			Handler:    _AispCoreService_DeleteConversation_Handler,
		},
		{
			MethodName: "CreateDialogue",
			Handler:    _AispCoreService_CreateDialogue_Handler,
		},
		{
			MethodName: "GetDialogue",
			Handler:    _AispCoreService_GetDialogue_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "CreateDialogueStream",
			Handler:       _AispCoreService_CreateDialogueStream_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "main.proto",
}

const (
	AdminService_CreateTenant_FullMethodName = "/luca.aisp.core.AdminService/CreateTenant"
	AdminService_GetTenant_FullMethodName    = "/luca.aisp.core.AdminService/GetTenant"
)

// AdminServiceClient is the client API for AdminService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AdminServiceClient interface {
	CreateTenant(ctx context.Context, in *CreateTenantRequest, opts ...grpc.CallOption) (*Tenant, error)
	GetTenant(ctx context.Context, in *GetTenantRequest, opts ...grpc.CallOption) (*Tenant, error)
}

type adminServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAdminServiceClient(cc grpc.ClientConnInterface) AdminServiceClient {
	return &adminServiceClient{cc}
}

func (c *adminServiceClient) CreateTenant(ctx context.Context, in *CreateTenantRequest, opts ...grpc.CallOption) (*Tenant, error) {
	out := new(Tenant)
	err := c.cc.Invoke(ctx, AdminService_CreateTenant_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) GetTenant(ctx context.Context, in *GetTenantRequest, opts ...grpc.CallOption) (*Tenant, error) {
	out := new(Tenant)
	err := c.cc.Invoke(ctx, AdminService_GetTenant_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AdminServiceServer is the server API for AdminService service.
// All implementations must embed UnimplementedAdminServiceServer
// for forward compatibility
type AdminServiceServer interface {
	CreateTenant(context.Context, *CreateTenantRequest) (*Tenant, error)
	GetTenant(context.Context, *GetTenantRequest) (*Tenant, error)
	mustEmbedUnimplementedAdminServiceServer()
}

// UnimplementedAdminServiceServer must be embedded to have forward compatible implementations.
type UnimplementedAdminServiceServer struct {
}

func (UnimplementedAdminServiceServer) CreateTenant(context.Context, *CreateTenantRequest) (*Tenant, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateTenant not implemented")
}
func (UnimplementedAdminServiceServer) GetTenant(context.Context, *GetTenantRequest) (*Tenant, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTenant not implemented")
}
func (UnimplementedAdminServiceServer) mustEmbedUnimplementedAdminServiceServer() {}

// UnsafeAdminServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AdminServiceServer will
// result in compilation errors.
type UnsafeAdminServiceServer interface {
	mustEmbedUnimplementedAdminServiceServer()
}

func RegisterAdminServiceServer(s grpc.ServiceRegistrar, srv AdminServiceServer) {
	s.RegisterService(&AdminService_ServiceDesc, srv)
}

func _AdminService_CreateTenant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTenantRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).CreateTenant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_CreateTenant_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).CreateTenant(ctx, req.(*CreateTenantRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_GetTenant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTenantRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).GetTenant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_GetTenant_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).GetTenant(ctx, req.(*GetTenantRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AdminService_ServiceDesc is the grpc.ServiceDesc for AdminService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AdminService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "luca.aisp.core.AdminService",
	HandlerType: (*AdminServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateTenant",
			Handler:    _AdminService_CreateTenant_Handler,
		},
		{
			MethodName: "GetTenant",
			Handler:    _AdminService_GetTenant_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "main.proto",
}
