// const string __VERSION__ = '0.0.130'
syntax = "proto3";

option java_package = "com.zhihu.aisp.core.service";
option java_multiple_files = true;
option java_outer_classname = "AispCoreServiceProto";
option go_package = "./aisp_core_service";

package aisp.core;
import "google/protobuf/wrappers.proto";

enum ChatStyle {
  UNDEFINED_STYLE = 0; // 未知
  THOROUGH = 1; // 深入
  SIMPLE = 2; // 简略
  DEEP_THINKING = 3; // 深度思考
}

enum ClientSource {
  UNDEFINED_SOURCE = 0; // 未知
  PC_WEB = 1; // Web端
  MOBILE_WEB = 2; // 移动Web端
  ZHIHU_APP = 3; // 知乎APP
}

// 为了和前端保持统一 这里为小写的枚举
enum TrafficSource {
  undefined_traffic = 0;                         // 未知
  zhida = 1;                                     // 直答主站调用
  ai_search_card = 2;                            // 从综搜首卡跳到直答 tab
  entity = 3;                                    // 实体词接入直答
  comment_entity = 4;                            // 实体词接入直答(comment)
  underlined_word = 5;                           // 划词跳直答
  noanswer_search = 6;                           // 某些问题下无回答出直答 bar
  ai_search_query = 7;                           // 在 PC 上点击搜索框出 AI 搜索词，点击某个词跳到直答
  suggestion = 8;                                // 在 PC 上搜索的 sug 词中的某一个点击后也会跳到直答
  below_banner_question = 9;                     // 回答详情页出相关追问，点击跳转直答
  right_banner_question = 10;                    // PC 上回答详情页右边栏出直答广告位，点击跳直答
  ai_summary_under_answer = 11;                  // 在 mobile_web 上，回答底部出 ai 总结跳直答
  unsatisfied_search = 12;                       // 搜索结果页无搜索结果时出直答 bar
  search_tab = 13;                               // 知乎搜索结果页独立 tab
  follow_query = 14;                             // 搜索结果页出追问，点击跳直答
  viewpoint_page = 15;                           // 有观点搜索卡底部出跳直答
  question_edit_page = 16;                       // 创作端问题编辑页出相似问题时跳直答一键总结
  ai_search_card_preview = 17;                   // 综搜首卡（半弹层）
  entity_preview = 18;                           // 实体词实体（半弹层）
  search_tab_preview = 19;                       // 知乎搜索结果页独立 tab（半弹层）
  zhida_pro = 20;                                // 专业版直答
  zhida_gr_demo = 21;                            // 直答GR demo
  ai_search_card_full_search_preview = 22;       // 综搜首卡-全网搜索（半弹层）
  ai_search_card_full_search = 23;               // 综搜首卡-全网搜索
  internal_qa = 24;                              // 内部问答
  zhida_word_interpretation = 25;                // 直答-划词解释
  zhida_translation = 26;                        // 直答-翻译
  commercial_data_insight = 27;                  // 商业数据洞察（有数）接入
  zhida_summary = 28;                            // 直答-私有召回内容摘要总结（无版权文档等等）
  zhida_knowledge_ground = 29;                   // 直答-知识广场
  search_entity_preview = 30;                    // 实体词 - 跳综搜
  ai_search_general = 31;                        // AI 搜索-通用
  ai_search_hotspot = 32;                        // AI 搜索-热点
  ai_search_koc = 33;                            // AI 搜索-koc
}

enum ChatFocusDomain {
  UNDEFINED_DOMAIN = 0; // 未知
  ALL = 1; // 全网
  SPECIALTY = 2; // 专业
}

// 内容类型
enum DocType {
  UNKNOWN_DOCTYPE = 0;    // 未知
  ANSWER = 1;             // 回答
  ARTICLE = 2;            // 文章
  TEXTS = 3;              // 文本
  USER_KNOWLEDGE = 4;     // 用户主动编辑知识
  UNIVERSAL_OFFSITE = 5;  // 站外通用知识
  COMMENT = 6;            // 评论
  PAPER = 7;              // 内容平台论文
  ZHI_DA_USER_UPLOAD = 8; // 直答用户上传
  MEMBER = 9;             // 用户
  EXTERNAL_WEBPAGE = 10;  // 外部网页
  INTERNAL_DOC = 11;      // 公司内部文档
  AISP_USER_UPLOAD = 12;  // AISP用户上传
}

enum PersonalKnowledgeBaseType {
  PKB_UNDEFINED = 0;        // 未知
  PKB_FAV = 1;              // 收藏
  PKB_RSS = 2;              // RSS订阅
  PKB_FOLDER = 3;           // 个人文件夹
  PKB_INTERNAL = 4;         // 公司内部文档上传
}

// 知识库可见性，包括私密和公开
enum KnowledgeBaseVisibility {
  UNDEFINED_VISIBILITY = 0; // 未知
  PRIVATE = 1;              // 私密
  PUBLIC_FEATURE = 2;       // 发布公开，可以被推荐到知识广场
  PUBLIC_ONLY = 3;          // 发布公开，不能被推荐到知识广场
}

enum KnowledgeBaseScene {
  UNDEFINED_SCENE = 0;        // 未知
  PERSONAL_ZHIDA = 1;         // 直答个人知识库，to-c
  INTERNAL_DOCUMENT = 2;      // 企业内部文档知识库，to-b 内部
}

enum ChatMessageType {
  EMPTY = 0; // 空消息
  TEXT = 1; // 文本消息
}

enum ChatCardType {
  UNDEFINED = 0; // 未知
  RELEVANT_SOURCE = 1; // 相关召回源
}

enum ChatType {
  CHAT = 0; // 自由对话
  AI_TAB = 1; // AI Tab
  SEARCH_TAB = 2; // 搜索 Tab
  DIGITAL_AUTHOR = 3; // 创作者数字分身
  ZHIHAITU = 4; // 知海图
  DEMO = 5; //DEMO
  AI_TAB_XC = 6; // AI Tab 瞎扯 bot
  AI_TAB_ZWKD = 7; // AI Tab 知问快答
  DISCOVER_TAB = 8; // 发现 Tab
  DOC_QA_AI = 9; // 文章问答AI
  PC_DISCOVER_TAB = 10; // 发现 Tab
  ZHIDA_TAB = 11; // 直答 Tab
  ZPLUS_BRAND = 12; // 知+品牌直答
  ZHIDA_PRO_TAB = 13; // 直答 Tab
  ZHIDA_V2 = 14; // 直答 v2
  ZHIDA_AGENT = 15; // 直答 Agent
  ZHIDA_MCP = 16; // 直答 mcp
}

enum ChatState {
  INITIALIZATION = 0; // 初始状态
  PROCESSING = 1; // 处理中
  COMPLETED = 2; // 已完成
  CANCELED = 3; // 已取消
  DELETED = 4; // 已删除
}

enum SuggestQueriesType {
  SUGGEST_QUERIES_UNDEFINED = 0; // 未定义
  AI_TAB_GUIDE = 1; // AI Tab 引导词
  SEARCH_TAB_GUIDE = 2; // 搜索 Tab 引导词
  AI_TAB_RELATED = 3; // AI Tab 相关词
  DISCOVER_TAB_GUIDE = 4; // 发现 Tab 引导词
  DOC_QA_AI_RELATED = 5; // 文章问答AI 相关词
  ZHIDA_TAB_GUIDE = 6; // 直答 Tab 引导词
  ZHIDA_TAB_RELATED = 7; // 相关词
  ASK_AGAIN_RELATED = 8; // 追问相关词
  SEARCH_ASK_AGAIN_RELATED = 9; // 搜索追问相关词
  SPECIFIED_DOC_RELATED = 10; // 单篇文档相关词
}

enum QueryType {
  QUERY_UNDEFINED = 0; // 未定义
  GUESS_WORD = 1; // 猜你想搜词
  PARAGRAPH = 2; // 段落词
  INTEREST_EXPANSION = 3; // 兴趣拓展
  RELATE_WORD = 4; // 相关词
  PREFAB_WORD_QUESTION = 5; // 预制词-问题
  PREFAB_WORD_HOT_QUESTION = 6; // 预制词-热榜问题
  RELATE_WORD_QUESTION = 7; // 相关词-问题
  RELATE_WORD_HOT_EVENT = 8; // 预制词-热点事件
}

enum BuildQueryType {
  BUILD_QUERY_UNDEFINED = 0; // 未定义
  SEARCH_TAB_SEARCH_CARD = 1; // 搜索卡片
}

enum ChatRespType {
  UNKNOWN_RESP = 0; // 未知返回，AI或后端返回的会带上下面type，如果用户主动填写的则为unknow
  GREETING = 1;     // 创作者问候语，初始进入会话场景默认返回的问候语
  DOMAIN = 2;       // 领域返回
  NON_DOMAIN = 3;   // 非领域相关回答
  SMALL_TALK = 4;   // 闲聊类回答
  REFUSE = 5;       // 拒绝回答
  RED_LINE = 6;     // 红线必答
  TASK = 7;         // 出任务
  UNANSWERABLE = 8; // 无法回答
  FAQ = 9;          // 静态常见问答库
  PLAIN_TEXT = 10;  // 纯文本回答
}

enum ChatModel{
  CM_ZHI_HAI_TU = 0;        // 默认 - 知海图
  CM_DEEP_SEEK_R1 = 1;      // Deepseek R1
  CM_QWQ_32B = 2;           // QWQ 32B
}

enum TaskGoal {
  UNKNOWN_Goal = 0;
  TEL_NUMBER = 1; // 留资
  GOODS = 2; // 带货
}

enum Role {
  UNKNOWN_Role = 0;
  USER = 1;
  AI = 2;
}

// 为了和 openai 协议对齐 这里均为小写的枚举
enum RoleOpenAi {
  unknown_role_openai = 0;
  system = 1;
  user = 2;
  assistant = 3;
}

// 意图类型
enum IntentionType {
  UNKNOWN_INTENTION = 0;    // 未知
  IN_DOMAIN = 1;            // 领域内
  OUT_DOMAIN = 2;           // 领域外
  SMALL_TALKS = 3;          // 闲聊
  SEARCH_INTENTION = 4;     // 搜索意图
  NO_SEARCH_INTENTION = 5;  // 非搜索意图
  AMBIGUOUS = 6;            // 模糊意图
}

// 业务阶段
enum BusinessStage {
  UNKNOWN_SECURITY_STAGE = 0; // 未知
  QUERY = 1;                  // query
  QUERY_MERGE = 2;            // query merge
  GENERATION = 3;             // 模型生成
  INTENTION = 4;              // 意图识别
  RELEVANT_QUERY = 5;         // 相关词
  GENERATION_STREAM = 6;      // 流式模型生成
  RETRIEVAL = 7;              // 召回
}

enum DocKnowledgeBase {
  UNDEFINED_KNOWLEDGE_BASE = 0; // 未知
  KB_CHINESE = 1;                  // 中文
  KB_ENGLISH = 2;                  // 英文
  KB_ZHIHU = 3;                    // 知乎
}

enum KnowledgeBaseType {
  UNDEFINED_KNOWLEDGE_BASE_TYPE = 0; // 未知
  KBT_GLOBAL = 1;                    // 全网
  KBT_ZHIHU = 2;                     // 知乎精选
  KBT_PAPER = 3;                     // 论文
  KBT_PERSONAL_KNOWLEDGE_BASE = 4;   // 个人知识库
}


enum KbRecallSearchType {
  RST_UNDEFINED = 0;      // 未知
  RST_DOC = 1;            // 文档
  RST_FOLDER = 2;         // 文件夹
}

enum KbRecallSearchField {
  RSF_UNDEFINED = 0;        // 未知
  RSF_TITLE = 1;            // 标题
  RSF_ABSTRACT = 2;         // 摘要
  RSF_CONTENT = 3;          // 正文
  RSF_DESCRIPTION = 4;      // 描述-当前只有知识库有描述
  RSF_MEMBER_ID = 5;        // 用户id
}

enum KbActionType {
  AT_UNDEFINED = 0;      // 未知
  AT_INSERT = 1;         // 增
  AT_DELETED = 2;        // 删
  AT_UPDATE = 3;         // 改
}

enum AuthorityLevel {
  UNKNOWN_LEVEL = 0;    // 未知
  S = 1;                // 极高，如官方手册
  A = 2;                // 较高，如平台各类 wiki
  B = 3;                // 中等，如个人使用笔记
  C = 4;                // 低，如聊天记录
  D = 5;                // 已废弃文档
}

enum BizGroup{
  UNDEFINED_BIZ_GROUP = 0;        // 未知
  MACHINE_LEARNING_PLATFORM = 1;  // 机器学习平台
  COMMERCIAL = 2;                 // 商业
  PAYMENT_PLATFORM = 3;           // 支付中台
}

enum RetrievalType {
  RT_UNDEFINED = 0;       // 未知
  RT_SEARCH = 1;          // 查找
  RT_BROWSE = 2;          // 浏览
  RT_SELECT = 3;          // 选择
}


// ===================================================

message ChatMessage {
  string message_id = 1; // 消息唯一ID
  int64 timestamp_ms = 2; // 消息毫秒时间戳
  ChatMessageType type = 3; // 消息类型
  string text = 4; // 文本
}

message RequestInfo {
  string session_id = 1; // 会话ID
  ChatMessage message = 2; // 消息
  int64 member_id = 3; // 用户ID
}


message ChatRequest {
  ChatType type = 1; // 业务类型
  RequestInfo info = 2; // 请求信息
  string resp_message_id = 3; // 返回 消息唯一ID
  RequestHeader header = 4;   // 请求header
  ChatStyle chat_style = 5; // 对话风格
  repeated string recall_content_ids = 6; // 召回源ID
  string prev_message_id = 7; // 重答时使用，上一条消息ID（同一消息，多次重答时，要使用同一个初始query 的 messageId）
  ChatExtraInfo chat_extra_info = 8; // 额外附加信息

  // 将来需要逐步废弃掉 这三个字段
  repeated DocKnowledgeBase assignment_doc_knowledge_base = 9 [deprecated = true]; // 指定文档源 知乎、中文、英文（旧）
  repeated ChatCardProRelevantSource assignment_docs = 10 [deprecated = true];     // 指定文档（旧）
  repeated PersonalKnowledgeBase personal_knowledge_base = 11 [deprecated = true]; // 个人知识库源 收藏夹、RSS、文件夹 （旧 对于AISP都是文件夹的概念）

  repeated KnowledgeBaseType knowledge_bases = 12;      // 指定 知识库 全网、知乎精选、论文、个人知识库
  repeated ReferenceMount curr_reference_mount = 13;    // 当前引用挂载 指定文档等概念全部转化为挂载
  repeated ReferenceMount history_reference_mount = 14; // 历史引用挂载
  ChatModel chat_model = 15;                            // 模型选择 - 默认知海图
}

message ZhidaRecallRequest{
  int64 member_id = 1;                // 用户ID
  string query = 2;                   // 查询词
  int32 publish_time_start = 3;       // 内容发布时间始
  int32 publish_time_end = 4;         // 内容发布时间止
  int32 limit = 5;                    // 返回数量限制
  RecallExtInfo recall_ext_info = 10; // 召回扩展信息
}

message RecallExtInfo{
  ChatType chat_type = 1;                           // 业务类型
  ClientSource client_source = 2;                   // 客户端来源
  TrafficSource traffic_source = 3;                 // 流量来源
  string message_id = 4;                            // 用户原始请求 messageId
  string request_id = 5;                            // 本次请求的 requestId，由请求方生成，为 parent_request_id 裂变而成，多次召回时为了区分不同次请求
  string parent_request_id = 6;                     // 上游 requestId，前后端透传
  string intention = 7;                             // 意图识别结果
  repeated KnowledgeBaseType knowledge_bases = 8;   // 指定 知识库 全网、知乎精选、论文、个人知识库
  repeated ReferenceMount reference_mount = 9;      // 引用挂载 指定文档等概念全部转化为挂载
}

message ZhidaRecallResponse{
  repeated ZhidaRecallItem recallItems = 1; // 检索结果
}

message ZhidaRecallItem{
  int64 doc_id = 1;                                     // 文档ID
  DocType doc_type = 2;                                 // 文档类型
  string title = 3;                                     // 文档标题  当doc_type=站外时不为空
  string abstract = 4;                                  // 文档摘要  当doc_type=站外时不为空
  string content = 5;                                   // 文档正文  当doc_type=站外时不为空
  string url = 6;                                       // 文档URL  当doc_type=站外时 doc_id=0，url不为空
  string recallSource = 7;                              // 召回源
  double recallScore = 8;                               // 召回分数
  int64 knowledge_base_id = 9;                          // 知识库ID
  PersonalKnowledgeBaseType knowledge_base_type = 10;   // 知识库类型
}

message ReferenceMount {
  PersonalKnowledgeBase mount_base = 1; // 挂载个人知识库
  DocIdentity mount_doc = 2;            // 挂载Doc、站外网页、用户等
  MountText mount_text = 3;             // 挂载文本
}

message PersonalKnowledgeBase {
  PersonalKnowledgeBaseType knowledge_base_type = 1; // 知识库类型
  int64 knowledge_base_id = 2;                       // 知识库ID
  string knowledge_base_name = 3;                    // 知识库名称
  KnowledgeBaseVisibility visibility = 4;            // 知识库可见性
}
message MountText {
  string text = 1;
  DocIdentity ref_doc_id = 2;  // 参考 doc
  string ref_message_id = 3;   // 参考 消息唯一ID
}


message ChatExtraInfo {
  DocAboutQueriesRequest source_content = 1; // 源内容
  int64 match_order = 2; // 匹配顺序 从0开始
  ModelArgs model_args = 3; // 模型参数
  int64 operation_id = 4; // 操作ID
}

message ModelArgs {
  google.protobuf.Int32Value max_tokens = 1;
  google.protobuf.FloatValue temperature = 2;
  google.protobuf.FloatValue top_p = 3;
  google.protobuf.Int32Value top_k = 4;
  google.protobuf.FloatValue presence_penalty = 5;
  google.protobuf.FloatValue repetition_penalty = 6;
  repeated string stop = 7;
  google.protobuf.FloatValue frequency_penalty = 8;
  string previous_response_id = 9;
}

//// Chat Card 内容
// 知乎相关源
message ChatCardZhihuRelevantSource {
  int64 doc_id = 1;             // 文档ID
  string doc_type = 2;          // 文档类型(ContentType)
  string recall_content_id = 3; // 召回内容ID
}

// 其他相关源
message ChatCardOtherRelevantSource {
  string doc_title = 1;        // 文档标题
  string doc_url = 3;          // 文档URL
  string recall_content_id = 4; // 召回内容ID
  string doc_abstract = 5; // 文档摘要
}

// 相关召回源
message ChatCardProRelevantSource {
  string doc_id = 1;                           // 文档ID  当doc_type=站外时 doc_id=url
  DocType doc_type = 2;                        // 文档类型
  string doc_title = 3;                        // 文档标题  当doc_type=站外时 title不为空
  string doc_abstract = 4;                     // 文档摘要  当doc_type=站外时 doc_id=url, title、abs 不为空
  string keyword = 5;                          // 关键词
}

// ... 其他卡片类型

message ChatCard {
  oneof CardContent {
    ChatCardZhihuRelevantSource zhihu_relevant_source = 1;      // 知乎相关源
    ChatCardOtherRelevantSource other_relevant_source = 2;      // 其他相关源
    ChatCardProRelevantSource zhida_relevant_source = 3;        // 直答PRO相关源
  }
}


// 主Stage: STAGE_RETRIEVAL、STAGE_KEYWORDS、STAGE_REFERENCE、STAGE_THINK、STAGE_ANSWER
// 检索Stage: STAGE_KEYWORDS、STAGE_REFERENCE、STAGE_ANSWER
enum ChatStage {
  STAGE_RETRIEVAL = 0; // 检索
  STAGE_KEYWORDS = 1;  // 关键词
  STAGE_REFERENCE = 2; // 参考
  STAGE_THINK = 3;     // 思考
  STAGE_ANSWER = 4;    // 回答束
}

enum ChatStageState {
  CSS_UNKNOWN = 0;    // 未知
  CSS_BEGIN = 1;      // 开始
  CSS_PROCESSING = 2; // 运行中
  CSS_END = 3;        // 结束
}

// chat_stage=STAGE_RETRIEVAL 取 retrieval_response (树状结构)
// chat_stage=STAGE_KEYWORDS 取 retrieval_keywords
// chat_stage=STAGE_REFERENCE 取 cards
// chat_stage=STAGE_THINK 取 think
// chat_stage=STAGE_ANSWER 取 message
message ChatResponse {
  ChatState state = 1;                                // 状态
  ChatMessage message = 2;                            // 消息
  ChatRespType resp_type = 3;                         // 返回类型
  ExtraRespInfo extra_resp_info = 4;                  // 其他返回信息
  repeated Query relevant_queries = 5;                // 相关问题
  repeated ChatCard cards = 6;                        // 参考文献
  string req_session_id = 7;                          // 请求会话ID
  ChatStage chat_stage = 8;                           // 对话阶段
  repeated string retrieval_keywords = 9;             // 关键词
  string think = 10;                                  // 思考
  int32 view_count = 11;                              // 模型阅读数量
  repeated RetrievalResponse retrieval_response = 12; // 检索结果
  map<int32, CiteDict> cite_dict = 13;                // 角标字典
  map<string, int64> processing_duration = 14;        // 处理时长 key: stage value: duration (ms)
  map<int32, CiteDict> digital_cite_dict = 15;        // 数字角标字典
  ChatStageState chat_stage_state = 16;               // 对话阶段状态
  bool is_hit_cache = 17;                             // 是否命中缓存
}


// chat_stage=STAGE_KEYWORDS 取 retrieval_keywords
// chat_stage=STAGE_REFERENCE 取 cards
// chat_stage=STAGE_ANSWER 取 summary
message RetrievalResponse {
  ChatStage chat_stage = 1;                             // 对话阶段
  string retrieval_topic = 2;                           // 召回主题
  repeated string retrieval_keywords = 3;               // 召回关键词
  repeated ChatCardProRelevantSource refs = 4;          // 参考文献
  string summary = 5;                                   // 总结
  int32 view_count = 6;                                 // 模型阅读数量
  ChatStageState chat_stage_state = 7;                  // 对话阶段状态（与ChatStage 成对出现）
  RetrievalType retrieval_type = 8;                     // Retrieval类型 该类型主要是描述 整个 RetrievalResponse 是否结束，用于让后端可以判断循环状态
  ChatStageState retrieval_state = 9;                   // 对话阶段状态
  repeated KnowledgeBaseType knowledge_bases = 10;      // 指定 知识库 全网、知乎精选、论文、个人知识库
  repeated ReferenceMount curr_reference_mount = 11;    // 当前引用挂载 指定文档等概念全部转化为挂载
  ChatRespType resp_type = 12;                          // 返回类型
}

message CiteDict {
  int32 card_idx = 1;       // doc索引位置
  string snippet = 2;       // 摘要（含高亮 <highlight></highlight> 标签）
  string image_token = 3;   // 图片token
  string image_url = 4;     // 图片url（站外图片-如果有）
  string video_id = 5;      // 视频id
  CiteBizType biz_type = 6; // 业务类型
}

enum CiteBizType {
  DEFAULT_BIZ_TYPE = 0; // 默认业务类型
  IN_PERSON = 1;        // 亲自答卡片（此时没有snippet，而是回答/文章大卡）
}

message ExtraRespInfo {
  int64 task_id = 1;  // 如果命中任务卡，返回任务id
  string summary = 2; // 任务生成摘要
}

message SuggestQueriesRequest {
  SuggestQueriesType type = 1; // 业务类型
  RequestInfo info = 2; // 请求信息
  ExtraInfo extra_info = 3; // 额外信息
  RequestHeader header = 4;   // 请求header
  DocAboutQueriesRequest doc_about_queries_request = 5; // 文档相关词请求
  repeated DocAboutQueriesRequest specified_doc_about_queries_request = 6; // 指定文档相关词请求
}

message Query {
  QueryType query_type = 1; // 词业务类型
  string id = 2; // 词ID
  string query = 3; // 词
  string risk_type = 4; // 负反馈类型
}

message SuggestQueriesResponse {
  repeated Query queries = 1; // 词列表
}

message BuildQueryRequest {
  BuildQueryType type = 1; // 业务类型
  RequestInfo info = 2; // 请求信息
}

message BuildQueryResponse {
  Query query = 1; // 词
}


message CreateSessionRequest {
  int64 member_id = 1; // 用户ID
  ChatType type = 2; // 业务类型
  ExtraInfo extra_info = 3; // 额外信息
  repeated DialogMessageWrapper dialog_messages = 4; // 对话消息
}

message DialogMessageWrapper {
  DialogMessage query = 1;
  DialogMessage answer = 2;
}

message DialogMessage {
  string messageId = 1; // 消息唯一ID
  string message = 2; // 消息内容
}

message ExtraInfo {
  int64 author_id = 1; // 创作者 ID，适用于数字分身类业务
  DocQaExtraInfo doc_qa_extra_info = 2; // 问答AI（文档系列的） 业务属性字段

  // 直答AI
  ChatFocusDomain chat_focus_domain = 3; // 聚焦领域
  int64 share_session_id = 4; // 分享Session Id ( SessionId + endMessage时间戳 确定会话快照 )
  int64 share_end_message_id = 5; // 分享结尾messageId

  // 知+品牌
  repeated string brand_name = 6;    // 品牌名称
  repeated string industry_name = 7; // 行业名称
  repeated string business_line = 8; // 业务线

  // 直答AI
  repeated int64 share_message_ids = 9; // 分享链接时 允许用户指定勾选一部分message（需要配合share_session_id）
}

// 问答AI（文档系列的） 业务属性字段
message DocQaExtraInfo {
  int64 doc_id = 1; // 文档ID
  string content_type = 2; // 文档类型
  repeated DocQaExtraParagraphInfo paragraphs = 3;   // 段落信息
}

// 问答AI（文档系列的） 业务属性字段-段落信息
message DocQaExtraParagraphInfo {
  int64 paragraph_index = 1;   // 段落Index
  string paragraph_version = 2;   // 段落版本
}


message CreateSessionResponse {
  int64 session_id = 1; // Session ID
}

message DigitalAuthorRequestInfo {
  string conversation_id = 1;         // 对话id
  ChatMessage message = 2;            // 消息
  string resp_message_id = 3;         // 返回消息唯一ID
  string sender_id = 4;               // 发送者ID
  string receiver_id = 5;             // 接收者ID
  DigitalAuthorBizInfo biz_info = 6;  // 业务拓展信息
  bool is_exempt_security = 7;        // 是否豁免安全，仅供调试。默认false
  RequestHeader header = 8;           // 请求header
}

message RequestHeader {
  string ip = 1;                        // 客户端ip
  string device_id = 2;                 // 设备id，应该解密后的long型ID
  string runtime_id = 3;                // 用户runtimeID（取 header中 x-zst-r）
  string sdid = 4;                      // 用户sdid（取 header 中x-sdid）
  string app_version = 5;               // 客户端版本
  string os = 6;                        // Android IOS
  string udid = 7;                      // udid，用户 client_id，用于ab
  ClientSource client_source = 8;       // 客户端来源
  TrafficSource traffic_source = 9;     // 流量来源
  TrafficSource traffic_reference = 10; // 流量引用来源
  bool is_retry = 11;                   // 是否是重试请求
  string version = 12;                  // 请求版本 - 默认传v2
}

message DigitalAuthorBizInfo {
  repeated HistChatMessage hist_chat = 1;   // 会话历史
  repeated string bayes_firstcategory = 2;  // 创作者关联领域
  repeated TaskInfo tasks = 3;              // 创作者勾选任务
  bool enable_onsite = 4;                   // 开启站内知识库同步
  bool enable_universal = 5;                // 开启通用知识库兜底
  string author_name = 6;                   // 创作者名
  repeated string topic_names = 7;          // 创作者擅长回答方向
}

message HistChatMessage {
  ChatMessage message = 1;  // message
  string sender_id = 2;      // 发送人ID
  Role role = 3;            // 角色
  ChatRespType resp_type = 4;  // 回答类型
}

message TaskInfo {
  int64 id = 1;             // 任务 id
  string task_name = 2;     // 任务名称
  string description = 3;   // 任务描述
  TaskGoal goal = 4;        // 任务目标
  repeated GoodsInfo goods_info = 5; // 任务目标是带货的话，此处传带货链接
}

message GoodsInfo {
  string url = 1;            // 商品链接
}

// tracing 日志记录
message Tracing {
  string member_id = 1;                             // 请求用户id
  string message_id = 2;                            // message id，同当前请求唯一id
  string resp_message_id = 3;                       // 返回 message id
  string scene = 4;                                 // 图场景，api.bizType
  string request_info = 5;                          // 请求结构体，打json
  string response_info = 6;                         // 返回结构体，打json
  ProcessTracing process_tracing = 7;               // 链路过程 tracing
  repeated LogicTracing logic_tracing = 8 [deprecated = true];
  int64 record_time_ms = 9;                         // 记录时间ms
  string query = 10;                                // 原始query
  map<string, LogicTracing> logic_tracing_map = 11; // 算子 tracing, key 为算子名称
  string trace_id = 12;                             // trace id，前后端透传，含义同 request_id
  string middle_process = 13;                       // 中间过程 tracing
  string context_tracing = 14;                      // 上下文 tracing
  string session_id = 15;                           // 会话ID
  string traffic_source = 16;                       // 流量来源
  string event_chain_tracing = 17;                  // event tracing
  string hit_cache_resp_message_id = 18;            // 命中缓存时，此处不为空，存储缓存命中的 resp_message_id
}

message ContextTracing {
  string last_login_province = 1; // 最近一次登录省份
}

// 意图
message Intention {
  IntentionType intention_type = 1; // 意图类型，旧版
  string intention = 2;             // 意图内容，新版
}

message ProcessTracing {
  string history = 1;                             // 会话历史
  string query_merge = 2;                         // query merge
  Intention intention = 3;                        // 意图识别结果
  repeated SecurityTracing security_tracing = 4;  // 多环节安全
  repeated IndexTracing recall_index = 5;         // 全部检索，原始召回之后截取段落
  repeated IndexTracing final_index = 6;          // 最终检索，只包含有效检索，即：索引召回后通过排序截断
  repeated Prompt prompt = 7;                     // 多环节prompt
  repeated IndexTracing original_recall_item = 8; // 原始召回内容
  repeated LLMAnswer llm_answer = 9;              // 大模型回答
  bool is_hit_cache = 10;                         // 是否命中缓存
  string timeliness = 11;                         // 时效性
  bool is_user_cancelled = 12;                    // 用户取消生成
  repeated string experiments = 13;               // 实验信息 为了方便查询 按照如下格式存储 domain,key,value
  map<string, string> logic_config = 14;          // 算子 config
  string env = 15;                                // 环境
  map<string, int32> cost_time = 16;              // 耗时
}

message Prompt {
  BusinessStage stage = 1;    // 业务阶段
  string prompt_content = 2;  // prompt 内容
  string description = 3;     // 描述
}

message LLMAnswer {
  BusinessStage stage = 1;    // 业务阶段
  string answer = 2;          // 大模型回答
}

message SecurityTracing {
  BusinessStage stage = 1;              // 业务阶段
  string red_line = 2;                  // 红线必答
  bool do_security_review = 3;          // 是否执行安审
  bool is_pass = 4;                     // 安审接口通过状态
  string fail_reason = 5;               // 安审失败原因
  string knowledge_enhance = 6;         // 知识增强
  string faq = 7;                       // FAQ
  string knowledge_enhance_keyword = 8; // 命中知识增强的关键词
}

message IndexTracing {
  int64 doc_id = 1;                     // 来源docId
  DocType doc_type = 2;                 // 来源docType
  string text = 3;                      // 段落内容
  repeated RecallInfo recall_info = 4;  // 召回信息
  RankInfo rank_info = 5;               // 排序信息
  string title = 6;                     // 标题
  string url = 7;                       // url
  int64 publish_time = 8;               // 发布时间，单位秒
}

message RecallInfo {
  string recall_source = 1;             // 召回源名称
  string recall_tag = 2;                // 召回标签
  double recall_score = 3;              // 召回分数
  bool is_used = 4;                     // 是否使用
}

message RankInfo {
  double similar_score = 1; // 相似度分数
}

message LogicTracing {
  string logic_name = 1;              // 算子名称
  repeated string logic_input = 2;    // 算子输入
  repeated string logic_output = 3;   // 算子输出
  string edge_select = 4;             // 算子边选
  int64 start_time_ms = 5;            // 算子开始执行时间，毫秒时间戳
  int64 end_time_ms = 6;              // 算子执行结束时间，毫秒时间戳
  int64 cost_ms = 7;                  // 算子执行耗时，毫秒
  string logic_process = 8;           // 算子过程日志
  string logic_input_json = 9;        // 算子输入 json 版
  string logic_output_json = 10;      // 算子输出 json 版
}

message DocAboutQueriesRequest {
  int64 doc_id = 1;                   // 文档ID
  DocType doc_type = 2;               // 文档类型
  string title = 3;                   // 标题
  string abstract = 4;                // 摘要
}

message UpsertCommonResponse {
  int64 status = 1;
  string message = 2;
}

// ===================== tracing =====================

message TracingMiddleProcess {
  LlmRecord query_router = 1;           // query 路由
  LlmRecord query_merge = 2;            // query 合并
  map<string, RecallItems> recalls = 3; // 召回 doc
  repeated RerankItem reranks = 4;      // 重排 chunk
  LlmRecord summary = 5;                // 模型总结，即流式对话结果
  repeated RecallItem cards = 6;        // 端上露出参考文献 doc
  repeated string security = 7;         // 安全命中情况
}

message LlmRecord {
  string model_name = 1;                // 模型名称
  repeated MessageOpenai messages = 2;  // 对话，openai标准格式
  ModelArgs param = 3;                  // 模型参数
  string response = 4;                  // 模型回答
  string response_id = 5;               // 模型返回id
}

message RecallItem {
  int64 doc_id = 1;         // 召回 doc id
  string doc_type = 2;      // 召回 doc 类型，为 ai-proto 里 doc_type.string() 的值
  string title = 3;         // 标题
  string url = 4;           // url
  string desc = 5;          // 正文，有截断
  int32 display_order = 6;  // 客户端展示顺序，从 1 开始，-1 表示不展示
}

message RerankItem {
  int64 doc_id = 1;         // 段落对应的召回 doc id
  string doc_type = 2;      // 段落对应的召回 doc 类型
  string title = 3;         // 标题
  string url = 4;           // url
  string chunk = 5;         // 段落内容
  double score = 6;         // 段落打分
  bool is_llm_used = 7;     // 是否模型使用
}

message RecallItems {
  repeated RecallItem items = 1;
}

message MessageOpenai {
  RoleOpenAi role = 1;  // 角色
  string content = 2;   // 内容
}

// ===================== biz service =====================

message KbRecallSearchRequest {
  int64 member_id = 1;                                                    // 用户ID
  string query = 2;                                                       // query
  KbRecallSearchType recall_search_type = 3;                              // 召回类型
  repeated PersonalKnowledgeBaseType knowledge_base_type = 4;             // 知识库类型
  repeated KbRecallSearchField search_recall_field = 5;                   // 检索字段
  int64 limit = 6;                                                        // 限制数量
  KnowledgeBaseVisibility visibility = 7;                                 // 检索知识库的可见性范围
  repeated int64 knowledge_base_ids = 8;                                  // 知识库ID列表，用于扩展非当前用户创建的知识库
}

message KbRecallSearchResponse {
  repeated KbRecallSearchRelevantSource relevant_source = 1; // 召回源信息
}

// 相关召回源
message KbRecallSearchRelevantSource {
  KbRecallSearchType type = 1;                       // 召回类型
  int64 knowledge_base_id = 2;                       // 个人知识库ID
  PersonalKnowledgeBaseType knowledge_base_type = 3; // 个人知识库类型
  int64 doc_id = 4;                                  // 文档ID  type=RST_DOC 时，doc_id 有内容
  DocType doc_type = 5;                              // 文档类型 type=RST_DOC 时，doc_type 有内容
  string title = 6;                                  // 高亮内容-标题 type=RST_FOLDER 时，title 有内容， abstract 无内容
  string abstract = 7;                               // 高亮内容-摘要
  string content = 8;                                // 高亮内容-正文 （扩展字段，目前为空）
  string description = 9;                            // 高亮内容-描述 当前仅知识库有
  int64 member_id = 10;                              // 创建人ID
}

message BuildPersonalKnowledgeBaseIndexRequest {
  int64 member_id = 1;                               // 用户ID
  int64 doc_id = 2;                                  // 来源docId
  DocType doc_type = 3;                              // 来源docType
  int64 knowledge_base_id = 4;                       // 个人知识库ID
  string knowledge_base_name = 5;                    // 个人知识库名称
  PersonalKnowledgeBaseType knowledge_base_type = 6; // 个人知识库类型
  KbActionType action_type = 7;                      // 操作类型
  KnowledgeBaseScene scene = 8;                      // 知识库场景
  string knowledge_base_description = 9;             // 个人知识库描述
  KnowledgeBaseVisibility visibility = 10;           // 知识库可见性
}

message DocIdentity {
  int64 doc_id = 1;         // 文档ID
  DocType doc_type = 2;     // 文档类型
  string doc_name = 3;      // 文档名称
}

message DocMeta {
  string title = 1 ;                  // 标题
  string abstract = 2;                // 摘要
  string content = 3;                 // 正文
  int64 last_updated_time = 4;        // 最后更新时间，单位秒
  string url = 5;                     // url，例如 wiki 链接
  repeated string tags = 6;           // 标签
  AuthorityLevel authority_level = 7; // 权威性等级，权威性高的会被优先召回
  string source = 8;                  // 来源，如 wiki、金山文档、oncall、readme
  string file_oss_path = 9;           // 上传文件的 oss path，需要调用 oss 服务拿到 oss url 才能读取
  string file_oss_url = 10;           // 上传文件的 oss url，能直接读取
}

message UpsertKnowledgeBaseDocumentRequest{
  DocIdentity doc_identity = 1;         // 文档唯一标识，首次创建时不传，更新时必传
  DocMeta doc_meta = 2;                 // 文档元信息
  BizGroup biz_group = 3;               // 业务团队
  string operator = 4;                  // 操作人邮箱前缀，或 memberId
}

message UpsertKnowledgeBaseDocumentResponse{
  int64 status = 1;             // 状态码，0表示成功，非0表示失败
  string message = 2;           // 错误信息
  DocIdentity doc_identity = 3; // 创建文档ID、类型
}

// ===================== service =====================

service AispChatService {
  // 创建Session 会话 , Session下 messageId 需要调用方保障唯一
  rpc CreateSession(CreateSessionRequest) returns (CreateSessionResponse);
  // 流式对话
  rpc StreamChat(ChatRequest) returns (stream ChatResponse);
  // 数字分身业务对话
  rpc DigitalAuthorChat(DigitalAuthorRequestInfo) returns (stream ChatResponse);
  // 词推荐
  rpc SuggestQueries(SuggestQueriesRequest) returns (SuggestQueriesResponse);

  // ========================================

  // 请求合并
  rpc BuildQuery(BuildQueryRequest) returns (BuildQueryResponse);
}

service AispBizService {
  // 知识库召回搜索
  rpc KbRecallSearch(KbRecallSearchRequest) returns (KbRecallSearchResponse);
  // 构建知识库索引
  rpc BuildPersonalKnowledgeBaseIndex(BuildPersonalKnowledgeBaseIndexRequest) returns (UpsertCommonResponse);
  // 上传知识库文档
  rpc UpsertKnowledgeBaseDocument(UpsertKnowledgeBaseDocumentRequest) returns (UpsertKnowledgeBaseDocumentResponse);
}

service AispRecallService {
  rpc GetZhidaRecall(ZhidaRecallRequest) returns (ZhidaRecallResponse);
}